### ISSUE TITLE
cor_heatmap taxon_renamer or alternative option for labeling rows 

### ISSUE THREAD

**Issue by AngelicaMiraples** [david-barnett/microViz#146]
Hi David! 

I am trying my luck at generating some correlation plots, following your tutorials [here](https://david-barnett.github.io/microViz/articles/web-only/heatmaps.html#correlation-heatmaps). 

I would like to change the row labels to specify ASV number and Species level taxonomy. I had tried using the argument taxon_renamer, but cannot seem to find examples using it. 

Alternatively, the R package ComplexHeatmap::pheatmap has an argument, label_rows, which can do this easily if I have a matching character vector which lists all the names I would like to use as labels. 
cor_heatmap indicates arguments from the ComplexHeatmap::pheatmap package can be passed but when I had included in the code, an error appeared indicating the label_rows argument was unused. 

Below is my simple code:
`ps2 %>%
  cor_heatmap(cor = "spearman", vars = c("TissueType", "DevStage", "Replicate"),
              labels_row = tax_ASV_spp
              )
`
Error messaged: 
`Error in (function (matrix, col, name, na_col = "grey", color_space = "LAB",  : 
  unused argument (labels_row = c("ASV1 Acinetobacter calcoaceticus", "ASV2 Pantoea ananatis", "ASV3 Pantoea ananatis", "ASV5 Pantoea ananatis", "ASV7 Pantoea ananatis", "ASV13 Chryseobacterium indologenes", "ASV15 Pantoea ananatis", "ASV16 Pantoea ananatis", "ASV18 Pantoea ananatis", "ASV31 Allorhizobium-Neorhizobium-Pararhizobium-Rhizobium Genus", "ASV38 Pantoea ananatis", "ASV40 Delftia acidovorans", "ASV72 Chryseobacterium Genus", "ASV78 Erwinia Genus", "ASV79 Wolbachia Genus", "ASV80 Acinetobacter guillouiae", 
"ASV109 Chryseobacterium Genus", "ASV137 Pseudomonas Genus", "ASV170 Erwinia Genus", "ASV197 Erwinia persicina"))
`

Any help on this would be appreciated!

Thanks!
Angelica

**Comment by david-barnett** [comment]
Hi Angelica!

> cor_heatmap indicates arguments from the ComplexHeatmap::pheatmap 

close, but not quite right! 

It passes additional arguments to [ComplexHeatmap::Heatmap](https://rdrr.io/pkg/ComplexHeatmap/man/Heatmap.html) and in that function, the manual row labelling argument is called `row_labels`

**Comment by david-barnett** [comment]
I should add more documentation on how to use the taxon_renamer argument - this argument takes a function, which you have to write yourself, which will modify the vector of taxa names before using them as row or column labels.

By default it is the function `identity` - which changes nothing.

You could instead use a string manipulation function e.g. `taxon_renamer = function(x) stringr::str_remove(x, "[pcofg]__")` which is a common one I might use to remove g__ etc. from the start of labels.

Or define a custom name to label lookup function something like this

```r
taxon_data <- tibble::tribble(
  ~taxon_name, ~taxon_label,
  "Genus A", "Label A",
  "Genus B", "Label B",
  "Genus C", "Label C"
)

taxon_df <- as.data.frame(taxon_data)
rownames(taxon_df) <- taxon_df$taxon_name
taxon_df$taxon_name <- NULL

taxon_label_lookup <- function(taxon_names, df = taxon_df) as.vector(df[taxon_names, "taxon_label"])

# test if works 
taxon_label_lookup(c("Genus C", "Genus A", "Genus B"))
```

```
ps2 %>% cor_heatmap(
  cor = "spearman", vars = c("TissueType", "DevStage", "Replicate"), 
  taxon_renamer = taxon_label_lookup
)
```

The big advantage of this approach over manual labelling is that with manual labelling you can easily accidentally write the labels in the wrong order (`cor_heatmap` will by default reorder the taxa in the heatmap to cluster similar correlation patterns together) and **you will need to manually ensure that custom labels set with `row_labels` are consistent with the new order**. Otherwise you can turn the reordering off, `seriation_method = "Identity"`

**Comment by david-barnett** [comment]
assuming this issue is resolved, feel free to open new issue if not :)
