### ISSUE TITLE
RShiny app problems

### ISSUE THREAD

**Issue by marypiper** [david-barnett/microViz#25]
When testing out the RShiny app functionality with the corncob dataset, few of the Selections worked with the app or didn't change the plot. For example, for 'shape', the race option (in addition to many others) generated the error: 'Error: ids don't have the same length than str (most often, it occurs because of clipping)'. Also, the lasso it doesn't always allow accurate selection - the data points I encircle are not the only points selected. Not sure why some of the time it works and other times it doesn't.

**Comment by david-barnett** [comment]
Thanks for highlighting these issues. 

- I was aware that problems arise with the specifying the shape. This error is emitted by the ggiraph package that microViz depends on to provide the plot interactivity. I will try to isolate why this happens for some shape specifications and not others, and see what I can do to avoid this limitation or at least work around it more cleanly.
- Regarding your points about the lasso not always being accurate, I have not seen this, but I will investigate :) 
- Some of the options in the "Add:" menu are not expected to work with all ordination plots, and I should make this clearer in the documentation, or perhaps dynamically remove those options when they aren't applicable e.g.
   - taxa loadings cannot be drawn for distance-based ordinations
   - hulls and ellipses cannot be drawn without first mapping colour to a variable, to provide groups

**Comment by david-barnett** [comment]
I think I have resolved the issue with the shapes error (as far as is possible) in the latest development version. Since commit: c12e01f19da5b6bf3078950d5e4aa97890d5d124 the user can select only variables with a max of 5 distinct levels (not including NA) for use as the shape mapping. A custom shape palette is now used which avoids using the composite shapes that were used by ggplot2 default and were causing the ggiraph dependency's error:  `Error: ids don't have the same length than str (most often, it occurs because of clipping)`

I have also added a larger description of how to use the app to the ord_explore [docs](https://david-barnett.github.io/microViz/reference/ord_explore.html) that might help somewhat with the other problems. Of course, please do let me know if you still have some issues with ord_explore.

I can't reproduce your experience of inaccurate lasso selection, what OS and web browser are you using? Is it selecting nearby points or completely incorrect points? 
Thanks!
