### ISSUE TITLE
comp_barplot() option not to scale to 1

### ISSUE THREAD

**Issue by fconstancias** [david-barnett/microViz#41]
Hi David,

Thanks for the awesome package. I was wondering if we could skip the scaling to barplot to 1 using `comp_barplot()`. The rationale behind would be to be able to plot the proportion of selected ASV/taxa and plot their actual proportions.

I could not find the options from the actual arguments.

Thanks.

**Comment by david-barnett** [comment]
Hi Florentin, glad you are finding microViz useful :) 

I think you are looking for the `comp_barplot` argument `tax_transform_for_plot`, which you can set to "identity" instead of the default "compositional" scaling. 

I haven't included an example of doing this in the documentation, so here's one below, modified from the current help page. 
Was this what you wanted?

```r
library(microViz)
library(ggplot2)
data(dietswap, package = "microbiome")

 dietswap %>%
   ps_filter(timepoint == 1) %>%
   comp_barplot(tax_level = "Family", n_taxa = 8, tax_transform_for_plot = "identity") + 
   coord_flip()
```
![image](https://user-images.githubusercontent.com/33695702/162977514-7f6968e6-bf44-4eab-89a6-d74897a3097b.png)

**Comment by fconstancias** [comment]
That's perfect @david-barnett . Thanks
